-- Woodex part 2: the 7 remaining tables (quotes, invoices, projects, templates, chats, chat messages, bookings).
-- phpMyAdmin -> u128159657_woodex -> Import. Safe to run more than once.
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS wx_templates (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, data LONGTEXT NOT NULL, UNIQUE(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_quotes (id INT AUTO_INCREMENT PRIMARY KEY, no VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, data LONGTEXT NOT NULL, INDEX(no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_invoices (id INT AUTO_INCREMENT PRIMARY KEY, no VARCHAR(30) NOT NULL, quote_id INT NULL, data LONGTEXT NOT NULL, UNIQUE(quote_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_projects (id INT AUTO_INCREMENT PRIMARY KEY, data LONGTEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_chats (id INT AUTO_INCREMENT PRIMARY KEY, token CHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, name VARCHAR(120) NULL, phone VARCHAR(40) NULL, email VARCHAR(190) NULL,
  page VARCHAR(200) NULL, ip VARCHAR(64) NULL, status VARCHAR(10) NOT NULL DEFAULT 'open', mode VARCHAR(10) NOT NULL DEFAULT 'ai', agent_name VARCHAR(120) NULL, unread INT NOT NULL DEFAULT 0,
  needs TINYINT NOT NULL DEFAULT 0, last_text VARCHAR(255) NULL, lead_id INT NULL, alerted TINYINT NOT NULL DEFAULT 0, channel VARCHAR(8) NOT NULL DEFAULT 'web', vtype DATETIME NULL, atype DATETIME NULL, INDEX(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_chat_msgs (id INT AUTO_INCREMENT PRIMARY KEY, chat_id INT NOT NULL, t DATETIME NOT NULL, who VARCHAR(8) NOT NULL, name VARCHAR(120) NULL, text TEXT NOT NULL, att TEXT NULL, INDEX(chat_id, id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_bookings (id INT AUTO_INCREMENT PRIMARY KEY, created_at DATETIME NOT NULL, lead_id INT NULL, name VARCHAR(120) NOT NULL, phone VARCHAR(40) NOT NULL,
  email VARCHAR(190) NULL, type VARCHAR(20) NOT NULL, city VARCHAR(80) NULL, address VARCHAR(300) NULL, d DATE NOT NULL, tm CHAR(5) NOT NULL, dur SMALLINT NOT NULL DEFAULT 60,
  status VARCHAR(12) NOT NULL DEFAULT 'pending', staff_id INT NULL, note VARCHAR(1000) NULL, src VARCHAR(12) NULL, reminded TINYINT NOT NULL DEFAULT 0, INDEX (d)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
