-- WOODEX V20 DATABASE: all 16 tables + login (email: admin / password: admin)
-- Use EITHER the installer (https://woodex.com.pk/wx-install.php)  OR  phpMyAdmin -> u128159657_woodex -> Import this file.
-- Safe to run again: nothing is deleted.
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS wx_users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
        role VARCHAR(20) NOT NULL DEFAULT 'editor', pass_hash VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, pw_ver INT NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL, last_login DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_activity (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, user_name VARCHAR(120) NULL, action VARCHAR(60) NOT NULL,
        target VARCHAR(255) NULL, ip VARCHAR(64) NULL, created_at DATETIME NOT NULL, INDEX(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_settings (k VARCHAR(80) PRIMARY KEY, v TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_throttle (ip VARCHAR(64) PRIMARY KEY, n INT NOT NULL, t INT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_leads (id INT AUTO_INCREMENT PRIMARY KEY, created_at DATETIME NOT NULL, source VARCHAR(30) NOT NULL, page VARCHAR(200) NULL,
        name VARCHAR(120) NOT NULL, phone VARCHAR(40) NULL, email VARCHAR(190) NULL, service VARCHAR(190) NULL, message TEXT NULL, fields TEXT NULL,
        stage VARCHAR(20) NOT NULL DEFAULT 'new', assigned_to INT NULL, followup DATE NULL, value BIGINT NOT NULL DEFAULT 0, lost_reason VARCHAR(190) NULL,
        client_id INT NULL, tags VARCHAR(400) NULL, is_read TINYINT(1) NOT NULL DEFAULT 0, ip VARCHAR(64) NULL,
        INDEX(stage), INDEX(created_at), INDEX(client_id), company VARCHAR(120) NULL, designation VARCHAR(80) NULL, location VARCHAR(160) NULL, line VARCHAR(20) NULL, lead_type VARCHAR(20) NULL, project_type VARCHAR(60) NULL, budget VARCHAR(60) NULL, area VARCHAR(30) NULL, priority VARCHAR(10) NULL, quote_status VARCHAR(20) NULL, last_contact DATETIME NULL, next_at DATETIME NULL, next_type VARCHAR(20) NULL, INDEX wx_leads_next (next_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_lead_notes (id INT AUTO_INCREMENT PRIMARY KEY, lead_id INT NOT NULL, t DATETIME NOT NULL, user_name VARCHAR(120) NULL,
        text TEXT NOT NULL, sys TINYINT(1) NOT NULL DEFAULT 0, INDEX(lead_id), kind VARCHAR(20) NULL, outcome VARCHAR(190) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_clients (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, phone VARCHAR(40) NULL, email VARCHAR(190) NULL,
        company VARCHAR(120) NULL, city VARCHAR(80) NULL, address VARCHAR(300) NULL, notes TEXT NULL, created_at DATETIME NOT NULL, type VARCHAR(20) NULL, source VARCHAR(40) NULL, tags VARCHAR(400) NULL, line VARCHAR(20) NULL, designation VARCHAR(80) NULL, updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_notify_log (id INT AUTO_INCREMENT PRIMARY KEY, t DATETIME NOT NULL, event VARCHAR(12) NOT NULL, ref VARCHAR(120) NULL, name VARCHAR(160) NULL, channel VARCHAR(8) NOT NULL, dest VARCHAR(190) NOT NULL, result VARCHAR(255) NOT NULL, INDEX(t)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_wa_seen (mid VARCHAR(190) PRIMARY KEY, t DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wx_templates (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, data LONGTEXT NOT NULL, UNIQUE(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_quotes (id INT AUTO_INCREMENT PRIMARY KEY, no VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, data LONGTEXT NOT NULL, INDEX(no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_invoices (id INT AUTO_INCREMENT PRIMARY KEY, no VARCHAR(30) NOT NULL, quote_id INT NULL, data LONGTEXT NOT NULL, UNIQUE(quote_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_projects (id INT AUTO_INCREMENT PRIMARY KEY, data LONGTEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_chats (id INT AUTO_INCREMENT PRIMARY KEY, token CHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, name VARCHAR(120) NULL, phone VARCHAR(40) NULL, email VARCHAR(190) NULL,
  page VARCHAR(200) NULL, ip VARCHAR(64) NULL, status VARCHAR(10) NOT NULL DEFAULT 'open', mode VARCHAR(10) NOT NULL DEFAULT 'ai', agent_name VARCHAR(120) NULL, unread INT NOT NULL DEFAULT 0,
  needs TINYINT NOT NULL DEFAULT 0, last_text VARCHAR(255) NULL, lead_id INT NULL, alerted TINYINT NOT NULL DEFAULT 0, channel VARCHAR(8) NOT NULL DEFAULT 'web', vtype DATETIME NULL, atype DATETIME NULL, INDEX(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_chat_msgs (id INT AUTO_INCREMENT PRIMARY KEY, chat_id INT NOT NULL, t DATETIME NOT NULL, who VARCHAR(8) NOT NULL, name VARCHAR(120) NULL, text TEXT NOT NULL, att TEXT NULL, INDEX(chat_id, id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_bookings (id INT AUTO_INCREMENT PRIMARY KEY, created_at DATETIME NOT NULL, lead_id INT NULL, name VARCHAR(120) NOT NULL, phone VARCHAR(40) NOT NULL,
  email VARCHAR(190) NULL, type VARCHAR(20) NOT NULL, city VARCHAR(80) NULL, address VARCHAR(300) NULL, d DATE NOT NULL, tm CHAR(5) NOT NULL, dur SMALLINT NOT NULL DEFAULT 60,
  status VARCHAR(12) NOT NULL DEFAULT 'pending', staff_id INT NULL, note VARCHAR(1000) NULL, src VARCHAR(12) NULL, reminded TINYINT NOT NULL DEFAULT 0, INDEX (d)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- P39/P40: AI report + Telegram tables (the code also creates these on first use)
CREATE TABLE IF NOT EXISTS wx_ai_events (id INT AUTO_INCREMENT PRIMARY KEY, t DATETIME NOT NULL, chat_id INT NOT NULL, kind VARCHAR(12) NOT NULL, reason VARCHAR(20) NULL, INDEX(t), INDEX(chat_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_ai_unans (id INT AUTO_INCREMENT PRIMARY KEY, t DATETIME NOT NULL, last_t DATETIME NOT NULL, chat_id INT NULL, q VARCHAR(500) NOT NULL, qkey VARCHAR(120) NOT NULL, n INT NOT NULL DEFAULT 1, status VARCHAR(10) NOT NULL DEFAULT 'open', INDEX(status), INDEX(qkey)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_tg_seen (uid BIGINT PRIMARY KEY, t DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wx_tg_map (msg_id BIGINT NOT NULL, chat_id INT NOT NULL, t DATETIME NOT NULL, PRIMARY KEY(msg_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO wx_users (name,email,role,pass_hash,active,pw_ver,created_at) VALUES ('Admin','admin','owner','$2y$10$.xP9p.h.R3H7AaDj/wW1P.pB25YEM0qx07xus/3GmFkI4QCygXGw2',1,1,NOW()) ON DUPLICATE KEY UPDATE pass_hash=VALUES(pass_hash), role='owner', active=1;
