-- =============================================================================
--  DEV / STAGING LOGIN — TEMPORARY ACCOUNT FOR TESTING ONLY
-- =============================================================================
--  Generated by:  node tools/dev-user.mjs --write
--
--        email:     dev@woodex.local
--        password:  Woodex#Dev2026        <- type it exactly
--        role:      owner         (full access, so every screen opens)
--
--  The hash below is bcrypt, cost 10, written in the same `$2y$10$` form that
--  PHP's password_hash() produces — so `password_verify()` in api/admin.php accepts it. It was
--  verified against two independent bcrypt implementations (glibc crypt via python3 and the
--  bcryptjs reference JS build): both accept the correct password and reject a wrong one.
--
--  WHY THIS FILE EXISTS
--  The six rows seeded by `woodex-database.sql` carry the deliberately dead hash
--  `$2y$10$LOCKED.SEED...` — that is a security measure, not a typo. No seeded
--  account can be signed into, and the owner account is created by running
--  /wx-install.php once on a fresh database. This file is the shortcut for a
--  LOCAL or STAGING database where you want to reach the admin immediately.
--
--  ⚠  DO NOT RUN THIS AGAINST THE LIVE woodex.com.pk DATABASE.
--     It creates a full-access owner whose password is published in this
--     repository. If it has ever been run on a live database, delete the row
--     (statement at the bottom) and change the password of every owner account.
--
--  AFTER YOU ARE DONE TESTING — run the DELETE at the bottom of this file.
-- =============================================================================

INSERT INTO `wx_users` (`name`, `email`, `role`, `pass_hash`, `active`, `pw_ver`, `created_at`)
VALUES ('Dev Login (temporary)', 'dev@woodex.local', 'owner',
        '$2y$10$6vEJHf7iwjYPnpRsAAcQCu6vvQKU91CXIr3.e9SAImJCvab8kenAi',
        1, 1, NOW())
ON DUPLICATE KEY UPDATE
  `pass_hash` = VALUES(`pass_hash`),
  `role`      = 'owner',
  `active`    = 1,
  `pw_ver`    = `pw_ver` + 1;      -- +1 kills any session that was already open

-- Confirm it landed the way the login expects (active, owner, bcrypt):
--   SELECT id, email, role, active, LENGTH(pass_hash) AS hash_len FROM wx_users
--    WHERE email = 'dev@woodex.local';
--   expected: role=owner, active=1, hash_len=60

-- -----------------------------------------------------------------------------
--  CLEANUP — uncomment and run when testing is over
-- -----------------------------------------------------------------------------
-- DELETE FROM `wx_users` WHERE `email` = 'dev@woodex.local';
