# P36-B2 round 2: one more topic-specific section per original post.
POSTS = []
UL = lambda items: "<ul>" + "".join("<li>%s</li>" % i for i in items) + "</ul>"
P = lambda *ps: "".join("<p>%s</p>" % x for x in ps)
def S(h, *b): return [(h, "".join(b))]

EXTRA = {
"apartment-small-space-planning-lahore": S("Storage checklist for small apartments",
  UL(["A full-height wardrobe wall in each bedroom.", "A shoe cabinet and coat hooks at the entrance.", "Tall kitchen units up to the ceiling.", "Under-bed drawers or a storage bed.", "A vanity with drawers in the bathroom.", "A closed TV unit for cables and devices."]),
  P("Plan storage before furniture. In small homes, clutter is the biggest enemy of calm.")),
"architect-fee-lahore-2026": S("Approvals and drawings in Lahore",
  P("Most housing societies and authorities in Lahore require approved drawings before construction or major changes. Approval requirements, timelines and documents vary by society, so ask your architect which submissions they handle and which you must arrange.",
    "Keep copies of approved drawings safe. You will need them for future changes, utility connections and, if you sell, for buyers and their lawyers.")),
"interior-designer-vs-contractor-lahore": S("Working well with both",
  P("On many projects, the best result comes from a designer and a contractor working together. The designer defines what is built and checks quality; the contractor manages labour and delivery.",
    "Agree who is responsible for what in writing: drawings, purchasing, site supervision, quality checks and snagging. Clear roles prevent the most common disputes.")),
"lighting-design-layers-explained": S("Common lighting mistakes",
  UL(["Too many downlights in a grid, making the ceiling look like a cheese grater.", "One bright light for the whole room.", "Cool white light in living spaces.", "No light at the mirror, causing shadows on the face.", "Forgetting sockets for lamps."]),
  P("A few well-placed sources nearly always beat many identical ones.")),
"materials-that-survive-lahore-climate": S("Quick material guide",
  UL(["Floors: matt porcelain for busy areas, sealed stone for formal rooms.", "Kitchen cabinets: moisture-resistant board with sealed edges.", "Bathroom vanities: water-resistant carcass, quartz or solid surface top.", "Walls: washable paint in kitchens, corridors and children's rooms.", "Outdoor: treated timber or composite, stainless or powder-coated metal."])),
"interior-designer-cost-lahore-2026": S("Getting value from your designer",
  P("Share a clear brief, decide promptly and keep feedback consolidated in one message per round. Designers spend much of their time on revisions caused by unclear or changing instructions.",
    "Ask questions early. A ten-minute conversation about how you live, cook and entertain shapes the design more than any mood board.")),
"office-layout-mistakes-productivity": S("Before you sign a new office lease",
  UL(["Check the floor plate shape; deep, narrow floors are harder to plan.", "Count the windows and their orientation.", "Confirm AC capacity and zoning.", "Ask about power backup and IT riser access.", "Check washroom capacity for your headcount."])),
"dha-vs-bahria-town-interior-cost-lahore": S("Which suits your project better?",
  P("Interior design principles are the same in both areas; the real differences are house types, society rules and logistics. Choose your team based on experience with similar homes and clear communication, not the postcode.",
    "Visit completed or in-progress projects where possible, and ask how the team handles deliveries and approvals in your society.")),
"house-renovation-timeline-lahore": S("A simple weekly routine",
  UL(["One short site meeting each week at a fixed time.", "A written list of decisions needed in the next two weeks.", "Photos of progress shared after each meeting.", "Any change recorded in writing with its effect on cost and time."]),
  P("This routine keeps everyone aligned and prevents surprises at handover.")),
"wardrobe-design-cost-pakistan-2026": S("Finishes and their care",
  P("Laminate is durable and easy to clean. Lacquer and paint finishes look refined but can chip and show fingerprints. Veneer gives a natural wood look and needs occasional care.",
    "Whichever finish you choose, ask for a sample door to see it in your room's light, and check edge banding quality closely.")),
"kitchen-layouts-that-work-lahore-homes": S("Choosing the right layout",
  UL(["Straight: narrow rooms and apartments.", "L-shaped: most family kitchens; easy to add a small table.", "U-shaped: maximum storage and counter space.", "Parallel (galley): efficient for one cook in narrow rooms.", "Island: larger kitchens with room for clearances on all sides."])),
"1-kanal-house-interior-cost-lahore": S("Keeping a large house consistent",
  P("In a large house, it is easy for each room to look like a separate project. Choose a core palette of two or three woods, stones and metals and repeat them throughout.",
    "Use the same door style, handles, skirting and lighting colour temperature across the house. Variety then comes from furniture, art and fabrics.")),
"false-ceiling-cost-lahore-2026": S("Maintenance and repairs",
  P("A well-made gypsum ceiling needs little care beyond repainting. Cracks usually appear at joints when framing moves or jointing was rushed. Water stains signal a leak above that should be fixed before repairing the ceiling.",
    "Keep access panels clear and labelled so AC and electrical work never needs the ceiling cut open.")),
"kitchen-renovation-cost-lahore": S("Living without a kitchen",
  P("Plan a temporary kitchen during renovation: a microwave, kettle, small fridge and a table in another room. Use disposable plates for the noisiest weeks.",
    "Ask your team for the dates when water and gas will be off so you can plan around them.")),
"5-marla-house-renovation-cost-lahore": S("Before you start",
  UL(["Check the structure for cracks and damp.", "Test plumbing pressure and look for leaks.", "Inspect the electrical board and wiring age.", "List what works and what really needs to change.", "Set a budget with a contingency for hidden problems."])),
"3d-interior-design-cost-pakistan": S("3D views versus drawings",
  P("3D views show how a room will look; drawings show how it will be built. You need both. A project with renders but no working drawings leaves too much to guesswork on site.",
    'See how our <a href="/3d-visualization/">3D visualisation</a> studio links views to buildable drawings.')),
"modular-kitchen-price-pakistan-2026": S("Measuring and installation",
  P("Accurate measurements are taken after plaster and flooring are complete. Walls in Lahore homes are rarely perfectly straight, so installers use fillers and adjustable legs to get a clean fit.",
    "Check that the counter template is taken after cabinets are fixed, and that the sink and hob cut-outs match the actual appliances.")),
"restaurant-cafe-interior-cost-lahore": S("Planning for opening day",
  UL(["Book health and safety inspections early.", "Test kitchen equipment and exhaust before staff training.", "Do a soft opening to test service flow.", "Keep spare light bulbs, tiles and paint for quick fixes."])),
"office-fit-out-cost-pakistan-2026": S("Before handover",
  UL(["Test every power and data point.", "Check AC performance in each zone.", "Confirm the fire alarm and emergency lighting work.", "Collect as-built drawings and equipment manuals."])),
}
