#!/usr/bin/env python3
"""Woodex UI kit generator — 40 builder blocks (uk-* classes) adapted from Flowbite (MIT), Meraki UI (MIT) and Charts.css (MIT).
Writes frontend-v1/builder/uikit.js (appends to WX_TEMPLATES) and splices minified tools/uikit/uikit.css into frontend-v1/assets/v1.css.
Run from the repo root:  python3 tools/gen-uikit.py"""
import json, re, pathlib

R = pathlib.Path(__file__).resolve().parent.parent
FV = R / "frontend-v1"
IMG = ["/assets/img/img-df7c7a7703ae.webp", "/assets/img/img-a824b3688cd4.webp", "/assets/img/img-6f26e32ab200.webp", "/assets/img/img-27c481fa9a3d.webp",
       "/assets/img/img-fcc680fef653.webp", "/assets/img/img-af83a84f72d2.webp", "/assets/img/img-42bae79b5c89.webp", "/assets/img/img-c693554a31d5.webp",
       "/assets/img/img-81b231a6c390.webp", "/assets/img/img-5048d9095862.webp", "/assets/img/img-ffafc4c12c46.webp", "/assets/img/img-f655d51401e8.webp"]
P = {  # lucide-style icon paths (MIT)
    "ruler": '<path d="M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.4 2.4 0 0 1 0-3.4l2.6-2.6a2.4 2.4 0 0 1 3.4 0Z"/><path d="m14.5 12.5 2-2M11.5 9.5l2-2M8.5 6.5l2-2M17.5 15.5l2-2"/>',
    "home": '<path d="m3 10 9-7 9 7v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/><path d="M9 22V12h6v10"/>',
    "cube": '<path d="M21 16V8a2 2 0 0 0-1-1.7l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.7l7 4a2 2 0 0 0 2 0l7-4a2 2 0 0 0 1-1.7Z"/><path d="M3.3 7 12 12l8.7-5M12 22V12"/>',
    "hammer": '<path d="m15 12-8.5 8.5a2.1 2.1 0 0 1-3-3L12 9"/><path d="M17.6 15 22 10.6M20.9 11.7l-1.3-1.3a2 2 0 0 1 0-2.8l.6-.6-3-3-2.8 2.8-1.4-1.4"/>',
    "clock": '<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
    "shield": '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',
    "sofa": '<path d="M20 9V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v3"/><path d="M2 11v5a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5a2 2 0 0 0-4 0v2H6v-2a2 2 0 0 0-4 0ZM4 18v2M20 18v2"/>',
    "wallet": '<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>',
    "info": '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/>',
    "check": '<circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/>',
    "alert": '<path d="m21.7 18-8-14a2 2 0 0 0-3.4 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.7-3Z"/><path d="M12 9v4M12 17h.01"/>',
    "chat": '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
}
def ic(n): return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + P[n] + "</svg>"
def img(i, alt="Woodex Interior project", w=1600, h=1200): return f'<img src="{IMG[i % len(IMG)]}" alt="{alt}" loading="lazy" width="{w}" height="{h}">'
def sec(body, cls="", aria=""): return f'<section class="uk {cls}"{aria}><div class="wrap">{body}</div></section>'
def head(k, h, p="", left=False, btns=""): return f'<div class="uk-head{" l" if left else ""}"><p class="uk-k">{k}</p><h2>{h}</h2>' + (f'<p class="mut">{p}</p>' if p else "") + btns + "</div>"
BTN2 = '<div class="uk-btns"><a class="uk-b p" href="/contact/">Book a free consultation</a><a class="uk-b o" href="/projects/">See our projects</a></div>'
def form(fields, btn="Send enquiry", kind="website"):
    return f'<form class="wx-form uk-form" action="/api/forms.php" method="post" data-wx-form="{kind}">{fields}<button class="uk-b p" type="submit">{btn}</button></form>'
F_NAME_PHONE = '<div class="row"><label>Name<input type="text" name="name" autocomplete="name" required></label><label>Phone<input type="tel" name="phone" autocomplete="tel" required></label></div>'
F_SERVICE = '<label>Service<select name="service"><option>Interior design</option><option>Renovation</option><option>Office fit-out</option><option>Kitchen &amp; wardrobes</option><option>Architecture</option></select></label>'
F_MSG = '<label>Message<textarea name="message" rows="4" placeholder="Tell us about your space"></textarea></label>'

B = []
def add(i, name, cat, icon, html): B.append({"id": "uk-" + i, "name": name, "cat": "UI kit · " + cat, "icon": icon, "html": html})

# ---------------- Hero (4)
add("hero-center", "Hero · centered with trust row", "Hero", "✦", sec('<div class="uk-hero"><span class="uk-badge">★ 4.9 rating · 200+ projects in Lahore</span><h1 style="margin-top:18px">Interiors designed around the way you live</h1><p class="lead mut">Design, build and furniture from one team, with a fixed quotation and a single project manager.</p><div class="uk-btns" style="justify-content:center"><a class="uk-b p" href="/contact/">Book a free consultation</a><a class="uk-b o" href="/projects/">See our projects</a></div><div class="uk-logos"><span>DHA</span><span>Bahria Town</span><span>Gulberg</span><span>Johar Town</span><span>Model Town</span></div></div>'))
add("hero-form", "Hero · text + enquiry form", "Hero", "✉", sec('<div class="uk-split"><div><p class="uk-k">Free consultation</p><h1>Plan your home with a designer, not a salesman</h1><p class="mut">Share a few details and our design lead will call you within one working day.</p><ul class="uk-ck"><li>3D design before any work starts</li><li>Itemised quotation, no hidden costs</li><li>Own workshop for kitchens and wardrobes</li></ul></div><div class="uk-card">' + form(F_NAME_PHONE + F_SERVICE + F_MSG, "Request a call back") + '</div></div>', "cream"))
add("hero-img", "Hero · split with image and stats", "Hero", "◧", sec('<div class="uk-split"><div><p class="uk-k">Woodex Interior</p><h1>Design and build, delivered on time</h1><p class="mut">From 5 marla homes to corporate offices — one accountable team from drawing to handover.</p>' + BTN2 + '<div class="uk-g uk-g3" style="margin-top:36px"><div class="uk-stat"><b>200+</b><small class="mut">Projects</small></div><div class="uk-stat"><b>10 yrs</b><small class="mut">Experience</small></div><div class="uk-stat"><b>4.9★</b><small class="mut">Reviews</small></div></div></div><div class="uk-img">' + img(0) + '</div></div>'))
add("hero-dark", "Hero · dark centered", "Hero", "◼", sec('<div class="uk-hero"><p class="uk-k">Office fit-out</p><h1>Workspaces that people want to come back to</h1><p class="lead mut">Planning, MEP, joinery and furniture for offices of 1,000 to 50,000 sq ft.</p><div class="uk-btns" style="justify-content:center"><a class="uk-b g" href="/contact/">Get a fit-out quote</a><a class="uk-b o" href="/projects/">Office projects</a></div></div>', "navy"))

# ---------------- Features (5)
feats = [("ruler", "Measured design", "Laser-measured site survey and a layout that fits real furniture."), ("cube", "3D before you build", "See every room in 3D and approve it before work starts."), ("hammer", "Own workshop", "Kitchens, wardrobes and joinery made in our Lahore workshop."),
         ("clock", "Fixed timeline", "A written schedule with weekly progress updates on WhatsApp."), ("wallet", "Itemised quotation", "Every item priced up front — no surprise extras."), ("shield", "1-year warranty", "Workmanship warranty and after-sales support on every project.")]
add("feat-grid", "Features · icon grid (6)", "Features", "▦", sec(head("Why Woodex", "Everything handled by one team", "Design, build and furniture without juggling contractors.") + '<div class="uk-g uk-g3">' + "".join(f'<div class="uk-card"><div class="uk-ic">{ic(a)}</div><h3>{b}</h3><p class="mut" style="margin:0">{c}</p></div>' for a, b, c in feats) + "</div>"))
add("feat-list", "Features · list + image", "Features", "☰", sec('<div class="uk-split"><div class="uk-img">' + img(1) + '</div><div>' + head("Our approach", "Designed on paper, built without surprises", left=True) + "".join(f'<div class="uk-feat" style="margin-bottom:22px"><div class="uk-ic">{ic(a)}</div><div><h3>{b}</h3><p class="mut" style="margin:0">{c}</p></div></div>' for a, b, c in feats[:3]) + '</div></div>', "cream"))
add("feat-bento", "Features · bento gallery", "Features", "▚", sec(head("Services", "One studio, every room") + f'<div class="uk-bento"><a class="big" href="/interior-design/">{img(2)}<span class="cap"><b>Interior design</b>Homes, apartments and farmhouses</span></a><a href="/kitchen/">{img(3)}<span class="cap"><b>Kitchens</b></span></a><div class="txt"><b style="font-size:28px">200+</b><span class="mut">projects delivered</span></div><a class="wide" href="/office-fit-out/">{img(4)}<span class="cap"><b>Office fit-out</b>Design and build</span></a></div>'))
add("feat-steps", "Features · 4-step process", "Features", "①", sec(head("How it works", "From first call to handover") + '<ol class="uk-steps"><li><h3>Consultation</h3><p class="mut">Free call and site visit to understand your brief.</p></li><li><h3>Design</h3><p class="mut">Layouts, 3D views and material boards.</p></li><li><h3>Quotation</h3><p class="mut">Itemised price and written timeline.</p></li><li><h3>Build &amp; handover</h3><p class="mut">Weekly updates, snag list and warranty.</p></li></ol>', "cream"))
add("feat-compare", "Features · comparison (us vs them)", "Features", "⇄", sec(head("The difference", "Woodex vs a typical contractor") + '<div class="uk-cmp"><div class="uk-card"><h3>Woodex Interior</h3><ul class="uk-ck"><li>One contract for design, build and furniture</li><li>3D approval before work starts</li><li>Itemised quotation</li><li>Weekly WhatsApp updates</li></ul></div><div class="uk-card bad"><h3>Typical contractor</h3><ul class="uk-ck"><li>Separate designer, builder and carpenter</li><li>Decisions made on site</li><li>Lump-sum estimate</li><li>You chase for updates</li></ul></div></div>'))

# ---------------- Pricing (3)
def price(n, a, unit, items, hi=False, tag="Most popular"):
    return f'<div class="uk-card uk-price{" hi" if hi else ""}"' + (f' data-tag="{tag}"' if hi else "") + f'><h3>{n}</h3><div class="amt">{a} <small>{unit}</small></div><ul class="uk-ck">' + "".join(f"<li>{x}</li>" for x in items) + f'</ul><a class="uk-b {"g" if hi else "p"}" href="/contact/" style="justify-content:center">Get a quote</a></div>'
add("price-3", "Pricing · 3 packages", "Pricing", "₨", sec(head("Packages", "Clear pricing per square foot", "Starting prices — your quotation is itemised after the site visit.") + '<div class="uk-g uk-g3" style="align-items:stretch">' + price("Essential", "PKR 2,500", "/ sq ft", ["Layout + 2D drawings", "Standard finishes", "Project manager"]) + price("Signature", "PKR 4,000", "/ sq ft", ["Full 3D design", "Premium finishes", "Custom joinery", "1-year warranty"], True) + price("Bespoke", "Custom", "quote", ["Architect-led design", "Imported materials", "Furniture &amp; styling"]) + "</div>", "cream"))
rows = [("3D design", "y", "y", "y"), ("Custom kitchen", "n", "y", "y"), ("Imported fittings", "n", "n", "y"), ("Warranty", "6 months", "1 year", "2 years")]
add("price-table", "Pricing · comparison table", "Pricing", "▤", sec(head("Compare", "What each package includes") + '<div class="uk-scroll"><table class="uk-tbl"><thead><tr><th>Feature</th><th>Essential</th><th>Signature</th><th>Bespoke</th></tr></thead><tbody>' + "".join("<tr><td>" + r[0] + "</td>" + "".join(f'<td class="{v if v in "yn" else ""}">' + ("✓" if v == "y" else "—" if v == "n" else v) + "</td>" for v in r[1:]) + "</tr>" for r in rows) + "</tbody></table></div>"))
add("price-one", "Pricing · single offer banner", "Pricing", "◎", sec('<div class="uk-card" style="display:flex;gap:28px;align-items:center;justify-content:space-between;flex-wrap:wrap;padding:clamp(24px,4vw,44px)"><div><span class="uk-badge w">Limited offer</span><h2 style="margin-top:12px">Free 3D design with every kitchen order</h2><p class="mut" style="margin:0">Book before the end of the month. Valid for Lahore projects.</p></div><div class="uk-price" style="min-width:220px"><div class="amt">PKR 0 <small>design fee</small></div><a class="uk-b p" href="/contact/" style="justify-content:center">Claim the offer</a></div></div>'))

# ---------------- Stats & charts (5)
add("stats-row", "Stats · 4 numbers", "Stats & charts", "#", sec('<div class="uk-g uk-g4 uk-c">' + "".join(f'<div class="uk-stat"><b>{a}</b><small class="mut">{b}</small></div>' for a, b in [("200+", "Projects completed"), ("10", "Years in business"), ("35", "Designers &amp; craftsmen"), ("4.9★", "Average review")]) + "</div>", "navy"))
yrs = [("2021", 28), ("2022", 45), ("2023", 62), ("2024", 78), ("2025", 100)]
add("chart-col", "Chart · column (Charts.css style)", "Stats & charts", "▮", sec('<div class="uk-split"><div>' + head("Growth", "Projects delivered per year", "A steady climb since we opened our own workshop.", True) + '</div><figure style="margin:0" role="img" aria-label="Projects per year: ' + ", ".join(f"{a} {int(b*0.62)}" for a, b in yrs) + '"><ul class="uk-col">' + "".join(f'<li><b>{int(b*0.62)}</b><i style="--v:{b}%"></i></li>' for a, b in yrs) + '</ul><ul class="uk-col-l">' + "".join(f"<li>{a}</li>" for a, b in yrs) + "</ul></figure></div>", "cream"))
add("chart-bar", "Chart · horizontal bars", "Stats & charts", "▭", sec(head("What clients ask for", "Most requested services") + '<ul class="uk-hbar" role="img" aria-label="Share of projects by service">' + "".join(f'<li><span>{a}</span><i style="--v:{b}%"></i><b>{b}%</b></li>' for a, b in [("Full home interior", 38), ("Kitchens", 24), ("Office fit-out", 18), ("Renovation", 12), ("Architecture", 8)]) + "</ul>", "navy"))
add("chart-area", "Chart · area + donut", "Stats & charts", "◔", sec('<div class="uk-g uk-g2"><div class="uk-card"><h3>Enquiries this year</h3><p class="mut">Monthly website enquiries</p><div class="uk-area" role="img" aria-label="Enquiries rising through the year"><i style="--p:polygon(0 100%,0 70%,9% 62%,18% 66%,27% 50%,36% 54%,45% 40%,54% 44%,63% 30%,72% 34%,81% 20%,90% 24%,100% 10%,100% 100%)"></i></div></div><div class="uk-card"><h3>Project mix</h3><p class="mut">By type, last 12 months</p><div class="uk-pie" style="--a:45%;--b:80%" role="img" aria-label="Homes 45%, offices 35%, other 20%"></div><ul class="uk-leg"><li><i style="--c:#0c1628"></i>Homes · 45%</li><li><i style="--c:#b8956a"></i>Offices · 35%</li><li><i style="--c:#d9cdb9"></i>Other · 20%</li></ul></div></div>', "cream"))
add("chart-rings", "Chart · progress rings + bars", "Stats & charts", "◯", sec(head("Quality", "Numbers we track on every project") + '<div class="uk-g uk-g3 uk-c">' + "".join(f'<div><div class="uk-ring" style="--v:{v}"><b>{v}%</b></div><h3>{a}</h3><p class="mut">{b}</p></div>' for v, a, b in [(96, "On-time handover", "Projects finished on the agreed date"), (92, "Within budget", "No change to the signed quotation"), (98, "Would recommend", "Clients who would refer us")]) + '</div><div class="uk-prog" style="max-width:720px;margin:40px auto 0">' + "".join(f'<div><span>{a}<b>{v}%</b></span><i style="--v:{v}%"></i></div>' for a, v in [("Design stage", 100), ("Civil work", 80), ("Joinery", 55), ("Finishing", 20)]) + "</div>"))

# ---------------- Testimonials (3)
T = [("Ayesha K.", "DHA Phase 6", "The 3D views matched the final house exactly. Handover was on the promised date."), ("Bilal A.", "Office, Gulberg", "They moved our 60-person team into a new office without a single lost workday."), ("Sana T.", "Bahria Town", "Clear quotation, weekly photos on WhatsApp, and a kitchen we love.")]
def who(n, p, i): return f'<div class="uk-who"><span class="uk-av">{n[0]}</span><div><b>{n}</b><small>{p}</small></div></div>'
add("testi-grid", "Testimonials · 3 cards", "Testimonials", "❝", sec(head("Reviews", "What our clients say") + '<div class="uk-g uk-g3">' + "".join(f'<figure class="uk-card" style="margin:0"><div class="uk-stars" aria-label="5 stars">★★★★★</div><blockquote style="margin:0 0 18px"><p>{q}</p></blockquote>{who(n, p, i)}</figure>' for i, (n, p, q) in enumerate(T)) + "</div>", "cream"))
add("testi-big", "Testimonials · big quote", "Testimonials", "“", sec('<figure class="uk-c" style="margin:0"><div class="uk-stars">★★★★★</div><blockquote style="margin:0"><p class="uk-q">“Woodex handled the design, the build and the furniture. We only had one number to call — and they always answered.”</p></blockquote>' + who("Hamza R.", "1 Kanal home, DHA Phase 7", 0) + "</figure>", "navy"))
add("testi-logos", "Testimonials · sectors + rating", "Testimonials", "◇", sec('<div class="uk-c"><p class="uk-k">Sectors we work in</p><div class="uk-logos" style="margin-top:8px"><span>Homes</span><span>Offices</span><span>Restaurants</span><span>Clinics</span><span>Retail</span></div><p class="mut" style="margin-top:28px">★ 4.9 average from 180+ Google reviews</p></div>'))

# ---------------- Team (2)
TM = [("Usman Ali", "Principal designer"), ("Hira Shah", "Interior architect"), ("Faisal Khan", "Project manager"), ("Mehak Noor", "3D visualiser")]
add("team-grid", "Team · 4 photo cards", "Team", "☺", sec(head("Our team", "The people behind every project") + '<div class="uk-g uk-g4 uk-team">' + "".join(f'<div><div class="uk-img">{img(5 + i, n + ", " + r, 800, 800)}</div><b>{n}</b><small>{r}</small></div>' for i, (n, r) in enumerate(TM)) + "</div>"))
add("team-list", "Team · compact list", "Team", "≡", sec('<div class="uk-split"><div>' + head("Your project team", "One team from design to handover", "Every project gets a named designer, project manager and site supervisor.", True) + '</div><div class="uk-card">' + "".join(f'<div class="uk-row"><span class="uk-av">{n[0]}</span><div class="sp"><b>{n}</b><br><small class="mut">{r}</small></div><span class="uk-badge">{["Design", "Design", "Site", "3D"][i]}</span></div>' for i, (n, r) in enumerate(TM)) + "</div></div>", "cream"))

# ---------------- CTA (3)
add("cta-band", "CTA · dark banner", "Call to action", "➜", sec('<div class="uk-cta"><div><h2>Ready to plan your space?</h2><p>Free consultation and site visit anywhere in Lahore.</p></div><div class="uk-btns"><a class="uk-b g" href="/contact/">Book a consultation</a><a class="uk-b o" href="tel:+923000000000">Call us</a></div></div>'))
add("cta-news", "CTA · newsletter / tips signup", "Call to action", "✉", sec('<div class="uk-c"><h2>Design ideas in your inbox</h2><p class="mut">One short email a month: new projects, material tips and offers.</p>' + '<form class="wx-form uk-inl" action="/api/forms.php" method="post" data-wx-form="newsletter"><input type="hidden" name="name" value="Newsletter subscriber"><input type="email" name="email" placeholder="Your email" aria-label="Your email" required><button class="uk-b p" type="submit">Subscribe</button></form></div>', "cream"))
add("cta-wa", "CTA · WhatsApp", "Call to action", "☏", sec(f'<div class="uk-wa"><div style="display:flex;gap:16px;align-items:center"><div class="uk-ic" style="background:#25d366;color:#fff;margin:0">{ic("chat")}</div><div><h3 style="margin:0 0 4px">Prefer WhatsApp?</h3><p class="mut" style="margin:0">Send photos of your space and get ideas within the hour.</p></div></div><a class="uk-b" href="https://wa.me/923000000000" target="_blank" rel="noopener">Chat on WhatsApp</a></div>'))

# ---------------- Content (5)
Q = [("How much does interior design cost?", "Design starts from PKR 2,500 per sq ft including finishes. You receive an itemised quotation after the site visit."), ("How long does a project take?", "A typical 10 marla home takes 10–14 weeks from approved design to handover."), ("Do you work outside Lahore?", "Yes — we work across Punjab and Islamabad for full-home and office projects."), ("Can I see the design before paying for work?", "Yes. You approve the 3D design and the quotation before any work starts.")]
add("faq", "FAQ · accordion", "Content", "?", sec('<div class="uk-split" style="align-items:start"><div>' + head("FAQ", "Questions clients ask us", "Can’t find your answer? Message us on WhatsApp.", True) + '</div><div class="uk-faq">' + "".join(f"<details{' open' if i == 0 else ''}><summary>{a}</summary><p class=\"mut\">{b}</p></details>" for i, (a, b) in enumerate(Q)) + "</div></div>"))
add("tabs", "Tabs · 3 panels (no JS)", "Content", "⊟", sec(head("Services", "Choose what you need") + '<div class="uk-tabs"><input type="radio" name="uk-t1" id="uk-t1a" checked><input type="radio" name="uk-t1" id="uk-t1b"><input type="radio" name="uk-t1" id="uk-t1c"><div class="bar"><label for="uk-t1a">Homes</label><label for="uk-t1b">Offices</label><label for="uk-t1c">Kitchens</label></div>' + "".join(f'<div class="pn"><div class="uk-split"><div><h3>{a}</h3><p class="mut">{b}</p><ul class="uk-ck"><li>Free site visit</li><li>3D design</li><li>Fixed quotation</li></ul></div><div class="uk-img">{img(8 + i)}</div></div></div>' for i, (a, b) in enumerate([("Full home interiors", "Layouts, finishes, lighting and furniture for 5 marla to 2 kanal homes."), ("Office fit-out", "Design-and-build workspaces with MEP, joinery and furniture."), ("Kitchens &amp; wardrobes", "Made to measure in our workshop, installed by our own team.")])) + "</div>", "cream"))
add("timeline", "Timeline · vertical", "Content", "┆", sec('<div class="uk-split" style="align-items:start"><div>' + head("Our story", "Ten years of Woodex", left=True) + '</div><ol class="uk-tl">' + "".join(f"<li><time>{a}</time><h3>{b}</h3><p class=\"mut\">{c}</p></li>" for a, b, c in [("2016", "Studio opens in Lahore", "Two designers and one carpenter."), ("2019", "Own workshop", "Kitchens and wardrobes made in-house."), ("2022", "Office fit-out team", "First 20,000 sq ft corporate project."), ("2026", "200+ projects", "Homes, offices and hospitality across Punjab.")]) + "</ol></div>"))
add("blog-cards", "Blog · 3 article cards", "Content", "✎", sec(head("Insights", "Ideas for your next project") + '<div class="uk-g uk-g3">' + "".join(f'<article class="uk-post"><a class="uk-img" href="/insights/">{img(9 + i)}</a><span class="uk-badge">{t}</span><h3 style="margin-top:12px"><a href="/insights/">{h}</a></h3><p class="mut">{d}</p></article>' for i, (t, h, d) in enumerate([("Kitchens", "7 kitchen layouts that work in Pakistani homes", "Pros, cons and costs of each layout."), ("Budget", "What a 10 marla interior really costs in 2026", "A line-by-line breakdown."), ("Offices", "Planning an office for hybrid teams", "Desks, meeting rooms and quiet zones.")])) + "</div>"))
add("gallery", "Gallery · masonry", "Content", "▣", sec(head("Portfolio", "Recent projects") + '<div class="uk-gal">' + "".join(img(i, "Woodex project photo", 1200, [900, 1500, 1200, 800, 1400, 1000][i % 6]) for i in range(6)) + "</div>"))

# ---------------- Forms (2)
add("form-contact", "Form · contact + map", "Forms", "✆", sec('<div class="uk-split" style="align-items:stretch"><div class="uk-card"><h2>Talk to a designer</h2><p class="mut">We reply within one working day.</p>' + form(F_NAME_PHONE + '<label>Email <small>(optional)</small><input type="email" name="email" autocomplete="email"></label>' + F_MSG, "Send message") + '</div><div class="uk-map"><iframe title="Woodex Interior on Google Maps" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Woodex+Interior+Lahore&amp;output=embed"></iframe></div></div>', "cream"))
add("form-quote", "Form · detailed quote request", "Forms", "▥", sec('<div style="max-width:760px;margin:auto">' + head("Get a quotation", "Tell us about your project", "The more we know, the more accurate your estimate.") + '<div class="uk-card">' + form(F_NAME_PHONE + '<div class="row">' + F_SERVICE + '<label>Area (sq ft)<input type="number" name="area" min="100" placeholder="e.g. 2250"></label></div><div class="row"><label>City<input type="text" name="city" value="Lahore"></label><label>Budget<select name="budget"><option>Not sure yet</option><option>Under PKR 25 lakh</option><option>PKR 25–60 lakh</option><option>PKR 60 lakh – 1 crore</option><option>Above PKR 1 crore</option></select></label></div>' + F_MSG, "Request my quotation", "quote") + "</div></div>"))

# ---------------- Components (8)
add("alerts", "Alerts · info / success / warning", "Components", "ⓘ", sec(f'<div style="max-width:760px;margin:auto"><div class="uk-alert i" role="status">{ic("info")}<div><b>Site visits this week</b>Available Monday to Saturday, 10 am – 6 pm.</div></div><div class="uk-alert s" role="status">{ic("check")}<div><b>Offer extended</b>Free 3D design on kitchen orders until the end of the month.</div></div><div class="uk-alert w" role="status">{ic("alert")}<div><b>Eid holidays</b>Our office is closed for three days; WhatsApp stays open.</div></div></div>'))
add("badges", "Badges · tags row", "Components", "◉", sec('<div class="uk-c"><p class="uk-k">Popular searches</p><div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center"><span class="uk-badge d">Interior design</span><span class="uk-badge">Kitchens</span><span class="uk-badge">Wardrobes</span><span class="uk-badge ok">Renovation</span><span class="uk-badge b">Office fit-out</span><span class="uk-badge w">Offers</span></div></div>', "cream"))
add("page-head", "Page header · breadcrumb", "Components", "›", sec('<nav aria-label="Breadcrumb"><ol class="uk-crumb"><li><a href="/">Home</a></li><li><a href="/services/">Services</a></li><li aria-current="page">Kitchens</li></ol></nav><h1>Kitchens made in our own workshop</h1><p class="mut" style="max-width:640px">Made-to-measure kitchens with soft-close fittings, installed by our team.</p>', "cream"))
add("card-img", "Cards · 3 image cards with link", "Components", "▢", sec('<div class="uk-g uk-g3">' + "".join(f'<a class="uk-card" href="{u}" style="padding:0;overflow:hidden;color:inherit;text-decoration:none"><div class="uk-img" style="border-radius:0">{img(3 + i)}</div><div style="padding:20px"><h3>{a}</h3><p class="mut" style="margin:0">{b}</p></div></a>' for i, (a, b, u) in enumerate([("Homes", "Full interiors for every size of home.", "/interior-design/"), ("Offices", "Design-and-build workspaces.", "/office-fit-out/"), ("Renovation", "Upgrade without moving out.", "/renovation/")])) + "</div>"))
add("list-links", "List group · service links", "Components", "☷", sec('<div class="uk-split" style="align-items:start"><div>' + head("Explore", "Find the right service", left=True) + '</div><div class="uk-list">' + "".join(f'<a href="{u}"><span><b>{a}</b><br><small class="mut">{b}</small></span></a>' for a, b, u in [("Interior design", "Homes and apartments", "/interior-design/"), ("Renovation", "Kitchens, bathrooms, full homes", "/renovation/"), ("Office fit-out", "Design and build", "/office-fit-out/"), ("Architecture", "New homes and extensions", "/architecture/")]) + "</div></div>"))
add("stepper", "Stepper · project progress", "Components", "⋯", sec(head("Project status", "Where your project is today") + '<ol class="uk-stepper"><li class="done">Enquiry</li><li class="done">Design</li><li class="cur">Quotation</li><li>Build</li><li>Handover</li></ol>', "cream"))
add("rating", "Rating · review summary", "Components", "★", sec('<div class="uk-split"><div class="uk-c"><b style="font-size:64px;letter-spacing:-.03em">4.9</b><div class="uk-stars" style="font-size:22px">★★★★★</div><p class="mut">Based on 180+ Google reviews</p></div><div class="uk-prog">' + "".join(f'<div><span>{s} star{"s" if s > 1 else ""}<b>{v}%</b></span><i style="--v:{v}%"></i></div>' for s, v in [(5, 91), (4, 7), (3, 1), (2, 1), (1, 0)]) + "</div></div>"))
add("table", "Table · price list", "Components", "▦", sec(head("Price guide", "Typical starting prices") + '<div class="uk-scroll"><table class="uk-tbl"><thead><tr><th>Item</th><th>Starting price</th><th>Time</th></tr></thead><tbody>' + "".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in [("Kitchen (10 ft)", "PKR 450,000", "3–4 weeks"), ("Wardrobe (per ft)", "PKR 9,500", "2–3 weeks"), ("Full 10 marla interior", "PKR 45 lakh", "10–14 weeks"), ("Office fit-out (per sq ft)", "PKR 3,200", "6–12 weeks")]) + "</tbody></table></div>"))

assert len(B) == 40, len(B)
assert len({b["id"] for b in B}) == 40
js = "/* Woodex UI kit — 40 blocks (generated by tools/gen-uikit.py). Layouts adapted from Flowbite (MIT), Meraki UI (MIT) and Charts.css (MIT); uk-* classes in assets/v1.css. */\n(window.WX_TEMPLATES = window.WX_TEMPLATES || []).push.apply(window.WX_TEMPLATES, " + json.dumps(B, ensure_ascii=False, indent=0) + ");\n"
(FV / "builder" / "uikit.js").write_text(js)

css = (R / "tools" / "uikit" / "uikit.css").read_text()
css = re.sub(r"/\*.*?\*/", "", css, flags=re.S); css = re.sub(r"\s+", " ", css); css = re.sub(r"\s*([{};,>])\s*", r"\1", css).replace(";}", "}").strip()
v1 = (FV / "assets" / "v1.css").read_text()
block = "/*UK:START Woodex UI kit — Flowbite/Meraki UI/Charts.css (MIT) adaptations*/" + css + "/*UK:END*/"
v1 = re.sub(r"/\*UK:START.*?/\*UK:END\*/", lambda m: block, v1, flags=re.S) if "/*UK:START" in v1 else v1.rstrip() + "\n" + block + "\n"
(FV / "assets" / "v1.css").write_text(v1)
print("blocks:", len(B), "css bytes:", len(block), "cats:", sorted({b["cat"] for b in B}))
