#!/usr/bin/env python3
"""Generates frontend-v1/builder/templates-v26.js — 50 v26-style section templates (Phase 5).
Uses only t6-* classes (assets/v1.css) + existing .btn / .wrap. Woodex's own images and real contact details."""
import json, os
I = ["dce06249b137", "1d6ad6c77d0f", "c349a92a4ae0", "f655d51401e8", "1f4b4ef86cb5", "fcc680fef653", "6f26e32ab200", "5048d9095862",
     "5194dc486e09", "42bae79b5c89", "a824b3688cd4", "27c481fa9a3d", "df7c7a7703ae", "c693554a31d5", "af83a84f72d2", "81b231a6c390",
     "774a712057fc", "197da8ddab9b", "00e6912a64f2", "ffafc4c12c46", "e670623c742b", "e3ba33b612d6", "853f9698149b"]
def img(n, alt="Woodex Interior project", cls="", eager=False):
    c = ("t6-img " + cls).strip()
    return f'<figure class="{c}"><img src="/assets/img/img-{I[n % len(I)]}.webp" alt="{alt}"' + ("" if eager else ' loading="lazy"') + ' width="1600" height="1200"></figure>'
def raw(n, alt="Woodex Interior project"): return f'<img src="/assets/img/img-{I[n % len(I)]}.webp" alt="{alt}" width="1920" height="1280">'
def sec(tone, inner, extra=""): return f'<section class="t6 {tone}{extra}"><div class="wrap">{inner}</div></section>'
def head(k, h, p="", c=False): return f'<div class="t6-head{" c" if c else ""}"><p class="t6-k">{k}</p><h2>{h}</h2>{f"<p>{p}</p>" if p else ""}</div>'
def acts(dark=True, a="Start your project", b="View projects", bh="/projects/"):
    s = "wx-btn-dark" if dark else "wx-btn-light"
    return f'<div class="t6-acts"><a class="btn {s}" href="/contact/">{a}</a><a class="btn wx-btn-outline {s}" href="{bh}">{b}</a></div>'
SERV = [("Interior design", "Layouts, finishes and furniture planned around how you live.", "/interior-design/"),
        ("Fit out", "Offices, retail and hospitality delivered to programme.", "/fit-out/"),
        ("Turnkey", "One team from empty shell to handover.", "/turnkey-design-build/"),
        ("Renovation", "Kitchens, bathrooms and full-home upgrades.", "/renovation/"),
        ("Architecture", "Residential and commercial buildings, elevations and planning.", "/architecture/"),
        ("3D visualization", "Photoreal renders before a single wall is built.", "/3d-visualization/")]
STEPS = [("Brief & site visit", "We listen, measure and understand the space."), ("Concept", "Mood, layout and a first cost range."),
         ("3D design", "Photoreal views so you can decide with confidence."), ("Drawings & BOQ", "Detailed drawings and a clear bill of quantities."),
         ("Build", "Our own teams and workshop deliver on site."), ("Handover", "Snag list closed, space ready to use.")]
FAQ = [("How much does interior design cost in Lahore?", "It depends on size, scope and finishes. After a short site visit we share a clear range, then a detailed BOQ before work starts."),
       ("How long does a project take?", "Most homes take 8–16 weeks from approved design; commercial fit-outs are planned to your opening date."),
       ("Do you make the furniture yourselves?", "Yes. Woodex has its own furniture workshop, so pieces are made to fit the space."),
       ("Can I see the design before building?", "Every project includes 3D views, so you approve the look before anything is built."),
       ("Do you work outside Lahore?", "Yes — we regularly deliver in Islamabad, Karachi and other cities.")]
TST = [("Woodex handled everything from design to handover. The 3D views matched the finished home exactly.", "Ayesha K.", "DHA Lahore · Home"),
       ("Our office was delivered on time and on budget. The team was calm, clear and professional.", "Omar R.", "Gulberg · Office fit-out"),
       ("The kitchen they designed changed how our family uses the house.", "Sana M.", "Model Town · Renovation")]
TEAM = [("Design lead", "Interior design"), ("Project manager", "Site & delivery"), ("3D artist", "Visualization"), ("Workshop head", "Furniture")]
T = []
def add(cat, name, icon, html): T.append({"id": f"v26-{len(T)+1:02d}", "name": name, "cat": cat, "icon": icon, "html": html})

# ---------------- HERO (8)
add("Hero", "Hero · full image, bottom text", "🏠", f'<section class="t6 t6-hero">{raw(0,"Woodex interior")}<div class="wrap"><p class="t6-k">Woodex Interior · Lahore</p><h1>Spaces shaped by<br>purpose and identity</h1><p>Interior design, fit-out and furniture by one accountable team.</p>{acts(False)}</div></section>')
add("Hero", "Hero · centered with chips", "🎯", f'<section class="t6 t6-hero center">{raw(1)}<div class="wrap"><p class="t6-k">Design · Build · Furnish</p><h1>Interiors that<br>feel like yours</h1><p>From first sketch to final handover.</p>{acts(False)}<div class="t6-chips" style="justify-content:center"><span>Homes</span><span>Offices</span><span>Restaurants</span><span>Retail</span></div></div></section>')
add("Hero", "Hero · split text + image", "◧", sec("cream", f'<div class="t6-split"><div><p class="t6-k">Interior design studio</p><h1>Design that works as well as it looks</h1><p>Measured layouts, honest budgets and furniture made in our own workshop.</p>{acts()}</div>{img(2,"Living room","tall",True)}</div>'))
add("Hero", "Hero · dark with stats", "📊", sec("navy", f'<div class="t6-head" style="max-width:900px"><p class="t6-k">Since 2016</p><h1>One team for design, build and furniture</h1><p>200+ completed spaces across Pakistan.</p>{acts(False)}</div><div class="t6-stats"><div class="t6-stat"><b>2016</b><span>Practising from Lahore</span></div><div class="t6-stat"><b>200+</b><span>Completed spaces</span></div><div class="t6-stat"><b>6</b><span>Disciplines, one team</span></div><div class="t6-stat"><b>4</b><span>Cities served</span></div></div>'))
add("Hero", "Hero · service page", "🛠️", f'<section class="t6 t6-hero">{raw(3)}<div class="wrap"><p class="t6-k">Service</p><h1>Kitchen design<br>in Lahore</h1><p>Practical layouts, durable finishes and cabinetry made to measure.</p>{acts(False,"Get a quote","See kitchens")}</div></section>')
add("Hero", "Hero · minimal white", "▫️", sec("", f'<div class="t6-head" style="max-width:980px"><p class="t6-k">Woodex Interior</p><h1>Calm, considered interiors for homes and workplaces.</h1>{acts()}</div>{img(4,"Interior","wide",True)}'))
add("Hero", "Hero · image grid", "🧩", sec("cream", f'<div class="t6-split"><div><p class="t6-k">Portfolio</p><h1>Every project, built by our own teams</h1><p>Browse homes, offices and hospitality spaces we have delivered.</p>{acts(True,"Start your project","All projects")}</div><div class="t6-g g2">{img(5,"Project","tall",True)}<div class="t6-g">{img(6)}{img(7)}</div></div></div>'))
add("Hero", "Hero · city page", "📍", f'<section class="t6 t6-hero center">{raw(8)}<div class="wrap"><p class="t6-k">Islamabad · Rawalpindi</p><h1>Interior design<br>in Islamabad</h1><p>Site visits, 3D design and full delivery in the twin cities.</p>{acts(False,"Book a site visit","Our work")}</div></section>')
# ---------------- SERVICES (6)
cards = lambda tone="": "".join(f'<a class="t6-card" href="{h}" style="text-decoration:none;color:inherit"><span class="t6-num">{i+1:02d}</span><h3>{n}</h3><p>{d}</p></a>' for i, (n, d, h) in enumerate(SERV))
add("Services", "Services · 6 numbered cards", "🔢", sec("", head("What we do", "Design services that cover the whole space", "", True) + f'<div class="t6-g g3">{cards()}</div>'))
add("Services", "Services · dark cards", "🌙", sec("navy", head("Services", "Six disciplines, one team") + f'<div class="t6-g g3">{cards()}</div>'))
add("Services", "Services · image cards", "🖼️", sec("cream", head("Services", "Choose where to start") + '<div class="t6-g g3">' + "".join(f'<a href="{h}" style="text-decoration:none;color:inherit">{img(9+i,n)}<div class="t6-cap">{n}<small>→</small></div></a>' for i, (n, d, h) in enumerate(SERV)) + "</div>"))
add("Services", "Services · list + image", "📋", sec("", f'<div class="t6-split">{img(15,"Studio","tall")}<div><p class="t6-k">Our services</p><h2>Everything your space needs</h2><div class="t6-steps">' + "".join(f'<div><div><h3>{n}</h3><p>{d}</p></div></div>' for n, d, h in SERV[:4]) + "</div></div></div>"))
add("Services", "Services · 4 feature columns", "✦", sec("cream", head("Why Woodex", "Built around you", "", True) + '<div class="t6-g g4">' + "".join(f'<div><span class="t6-num">{i+1:02d}</span><h3>{a}</h3><p>{b}</p></div>' for i, (a, b) in enumerate([("One team", "Design, build and furniture under one contract."), ("Own workshop", "Furniture and joinery made to fit."), ("Clear budgets", "Detailed BOQ before work starts."), ("On schedule", "Weekly updates and a fixed programme.")])) + "</div>"))
add("Services", "Services · sub-services grid", "🗂️", sec("", '<div class="t6-row">' + head("Interior design", "What’s included") + '<a class="btn wx-btn-dark" href="/contact/">Get a quote</a></div><div class="t6-g g4">' + "".join(f'<div class="t6-card"><h3>{x}</h3><p>Planned, drawn and delivered by our team.</p></div>' for x in ["Living rooms", "Bedrooms", "Kitchens", "Bathrooms", "Home offices", "Dining", "Lighting", "Furniture"]) + "</div>"))
# ---------------- PROJECTS / GALLERY (6)
proj = [("Contemporary villa", "DHA Lahore"), ("Corporate office", "Gulberg"), ("Café interior", "MM Alam Road"), ("Family home", "Bahria Town"), ("Retail store", "Emporium"), ("Penthouse", "Islamabad")]
add("Projects", "Projects · 3 cards", "🏗️", sec("", '<div class="t6-row">' + head("Selected studies", "Recent projects") + '<a class="btn wx-btn-outline wx-btn-dark" href="/projects/">All projects</a></div><div class="t6-g g3">' + "".join(f'<a href="/projects/" style="text-decoration:none;color:inherit">{img(i,n,"tall")}<div class="t6-cap">{n}<small>{c}</small></div></a>' for i, (n, c) in enumerate(proj[:3])) + "</div>"))
add("Projects", "Projects · featured + 2", "⭐", sec("cream", head("Featured", "A closer look") + f'<div class="t6-split" style="align-items:stretch">{img(3,"Featured project","tall")}<div class="t6-g">' + "".join(f'<a href="/projects/" style="text-decoration:none;color:inherit">{img(4+i,n,"wide")}<div class="t6-cap">{n}<small>{c}</small></div></a>' for i, (n, c) in enumerate(proj[1:3])) + "</div></div>"))
add("Projects", "Projects · dark 6 grid", "🌃", sec("navy", head("Portfolio", "Homes, offices and hospitality", "", True) + '<div class="t6-g g3">' + "".join(f'<a href="/projects/" style="text-decoration:none;color:inherit">{img(6+i,n)}<div class="t6-cap">{n}<small>{c}</small></div></a>' for i, (n, c) in enumerate(proj)) + "</div>"))
add("Gallery", "Gallery · masonry", "🧱", sec("", head("Gallery", "Details that make the space", "", True) + '<div class="t6-masonry">' + "".join(img(10+i, "Interior detail") for i in range(6)) + "</div>"))
add("Gallery", "Gallery · 4 wide", "🎞️", sec("cream", '<div class="t6-g g4">' + "".join(img(16+i, "Interior", "tall") for i in range(4)) + "</div>"))
add("Projects", "Project · case study", "📄", sec("", f'<div class="t6-split"><div><p class="t6-k">Case study · DHA Lahore</p><h2>A 1-kanal home, redesigned for family life</h2><p>Open kitchen, warm timber and furniture made in our workshop.</p><div class="t6-stats" style="grid-template-columns:repeat(3,1fr);margin-top:28px"><div class="t6-stat"><b>14</b><span>Weeks</span></div><div class="t6-stat"><b>6</b><span>Rooms</span></div><div class="t6-stat"><b>1</b><span>Team</span></div></div></div>{img(12,"Case study","tall")}</div>'))
# ---------------- PROCESS (5)
add("Process", "Process · numbered list", "🪜", sec("", f'<div class="t6-split" style="align-items:start"><div>{head("How we work","Six clear steps","From first call to handover — you always know what happens next.")}</div><div class="t6-steps">' + "".join(f"<div><div><h3>{a}</h3><p>{b}</p></div></div>" for a, b in STEPS) + "</div></div>"))
add("Process", "Process · 4 cards dark", "🌙", sec("navy", head("Process", "Simple from start to finish", "", True) + '<div class="t6-g g4">' + "".join(f'<div class="t6-card"><span class="t6-num">{i+1:02d}</span><h3>{a}</h3><p>{b}</p></div>' for i, (a, b) in enumerate(STEPS[:4])) + "</div>"))
add("Process", "Process · 3 steps with images", "🖼️", sec("cream", head("Process", "Design, build, handover", "", True) + '<div class="t6-g g3">' + "".join(f'<div>{img(13+i,a)}<span class="t6-num" style="margin-top:18px">{i+1:02d}</span><h3>{a}</h3><p>{b}</p></div>' for i, (a, b) in enumerate([STEPS[2], STEPS[4], STEPS[5]])) + "</div>"))
add("Process", "Process · timeline 6", "⏱️", sec("", head("Timeline", "What a typical project looks like") + '<div class="t6-g g3">' + "".join(f'<div class="t6-card"><span class="t6-num">Week {w}</span><h3>{a}</h3><p>{b}</p></div>' for (a, b), w in zip(STEPS, ["1", "2–3", "3–5", "5–6", "6–14", "14+"])) + "</div>"))
add("Process", "Process · split with checklist", "✅", sec("cream", f'<div class="t6-split">{img(18,"Site work","tall")}<div><p class="t6-k">What you get</p><h2>Every project includes</h2><ul class="t6-list"><li>Site visit and measurements</li><li>Concept and 3D views</li><li>Working drawings and BOQ</li><li>Own site teams and workshop</li><li>Weekly progress updates</li><li>Handover and aftercare</li></ul>{acts(True,"Book a site visit","Pricing","/estimator/")}</div></div>'))
# ---------------- FAQ (5)
ASK = 'Can’t find yours? <a href="/contact/">Ask us</a>.'
faq = lambda n=5: '<div class="t6-faq">' + "".join(f"<details{' open' if i == 0 else ''}><summary>{q}</summary><p>{a}</p></details>" for i, (q, a) in enumerate(FAQ[:n])) + "</div>"
add("FAQ", "FAQ · split", "❓", sec("", f'<div class="t6-split" style="align-items:start">{head("Common questions","Practical answers",ASK)}{faq()}</div>'))
add("FAQ", "FAQ · dark accordion", "🌙", sec("navy", head("FAQ", "Common questions", "", True) + f'<div style="max-width:820px;margin:auto">{faq()}</div>'))
add("FAQ", "FAQ · centered cream", "☕", sec("cream", head("Questions", "Before you start", "", True) + f'<div style="max-width:820px;margin:auto">{faq(4)}</div>'))
add("FAQ", "FAQ · with image", "🖼️", sec("", f'<div class="t6-split" style="align-items:start">{img(19,"Studio","tall")}<div><p class="t6-k">FAQ</p><h2>Good to know</h2>{faq(4)}</div></div>'))
add("FAQ", "FAQ · 2 columns cards", "🗂️", sec("cream", head("FAQ", "Quick answers", "", True) + '<div class="t6-g g2">' + "".join(f'<div class="t6-card"><h3>{q}</h3><p>{a}</p></div>' for q, a in FAQ[:4]) + "</div>"))
# ---------------- TESTIMONIALS (5)
who = lambda n, r, i: f'<div class="t6-who"><img src="/assets/img/img-{I[(i+5) % len(I)]}.webp" alt="" loading="lazy" width="96" height="96"><div><b>{n}</b><small>{r}</small></div></div>'
add("Testimonials", "Testimonials · 3 cards", "💬", sec("cream", head("Clients", "What clients say", "", True) + '<div class="t6-g g3">' + "".join(f'<div class="t6-card"><div class="t6-stars">★★★★★</div><p class="t6-quote" style="font-size:1.1rem">“{q}”</p>{who(n,r,i)}</div>' for i, (q, n, r) in enumerate(TST)) + "</div>"))
add("Testimonials", "Testimonial · big quote dark", "🗨️", sec("navy", f'<div style="max-width:900px;margin:auto;text-align:center"><div class="t6-stars">★★★★★</div><p class="t6-quote">“{TST[0][0]}”</p><p><b style="color:#f4efe7">{TST[0][1]}</b> · {TST[0][2]}</p></div>'))
add("Testimonials", "Testimonial · split image", "🖼️", sec("", f'<div class="t6-split">{img(20,"Client home","tall")}<div><p class="t6-k">Client story</p><p class="t6-quote">“{TST[1][0]}”</p>{who(TST[1][1],TST[1][2],1)}</div></div>'))
add("Testimonials", "Testimonials · rating + quotes", "⭐", sec("cream", f'<div class="t6-split" style="align-items:start"><div><p class="t6-k">Reviews</p><h2>Rated 4.9 by our clients</h2><div class="t6-stat"><b>4.9/5</b><span>Google reviews</span></div></div><div class="t6-g">' + "".join(f'<div class="t6-card"><p style="margin:0 0 14px">“{q}”</p>{who(n,r,i)}</div>' for i, (q, n, r) in enumerate(TST[1:])) + "</div></div>"))
add("Testimonials", "Trust · logos strip", "🏷️", sec("", '<p class="t6-k" style="display:block;text-align:center">Trusted by homeowners and brands</p><div class="t6-logos"><span>Emaar</span><span>DHA</span><span>Bahria</span><span>Gulberg Offices</span><span>Café Lahore</span><span>Retail Co.</span></div>'))
# ---------------- CTA / CONTACT (5)
CENTER = 't6-acts" style="justify-content:center'
add("CTA", "CTA · dark band", "📣", sec("", f'<div class="t6-band"><div><h2>Ready to plan your space?</h2><p>Share your brief — we reply within one working day.</p></div><div class="t6-acts" style="margin:0"><a class="btn wx-btn-light" href="/contact/">Start your project</a><a class="btn wx-btn-outline wx-btn-light" href="https://wa.me/923224000768">WhatsApp</a></div></div>'))
add("CTA", "CTA · full image", "🌅", f'<section class="t6 t6-hero center" style="min-height:60vh">{raw(21)}<div class="wrap"><h2 style="font-size:clamp(2.2rem,5vw,4rem)">Let’s shape the space</h2><p>Tell us what you are planning.</p>{acts(False,"Start your project","Cost estimator","/estimator/")}</div></section>')
add("CTA", "CTA · cream centered", "✉️", sec("cream", f'<div class="t6-head c" style="margin-bottom:0"><p class="t6-k">Next step</p><h2>Book a free site visit</h2><p>Lahore, Islamabad and Karachi.</p>{acts(True,"Book a visit","Call +92 322 4000768","tel:+923224000768").replace("t6-acts",CENTER)}</div>'))
add("Contact", "Contact · details + form", "📞", sec("", f'<div class="t6-split" style="align-items:start"><div><p class="t6-k">Contact</p><h2>Talk to Woodex</h2><p>M-71, Zainab Tower, Model Town Link Road, Lahore</p><ul class="t6-list"><li><a href="tel:+923224000768">+92 322 4000768</a></li><li><a href="tel:+923214686884">+92 321 4686884</a></li><li><a href="mailto:info@woodex.com.pk">info@woodex.com.pk</a></li><li>Mon–Sat 9:30–6:30</li></ul></div><form class="t6-form wx-form" action="/api/forms.php" method="post" data-wx-form="website"><input name="name" placeholder="Your name" required><input name="phone" type="tel" placeholder="Phone / WhatsApp" required><select name="service"><option>Interior design</option><option>Fit out</option><option>Renovation</option><option>Architecture</option></select><textarea name="message" rows="4" placeholder="Tell us about your space"></textarea><button class="btn wx-btn-dark" type="submit">Send enquiry</button></form></div>'))
add("Contact", "Contact · 3 cards dark", "🗂️", sec("navy", head("Get in touch", "We’re easy to reach", "", True) + '<div class="t6-g g3"><a class="t6-card" href="tel:+923224000768" style="text-decoration:none"><span class="t6-num">Call</span><h3>+92 322 4000768</h3><p>Mon–Sat 9:30–6:30</p></a><a class="t6-card" href="https://wa.me/923224000768" style="text-decoration:none"><span class="t6-num">WhatsApp</span><h3>Message us</h3><p>Quick replies during office hours</p></a><a class="t6-card" href="mailto:info@woodex.com.pk" style="text-decoration:none"><span class="t6-num">Email</span><h3>info@woodex.com.pk</h3><p>Send plans and photos</p></a></div>'))
# ---------------- STATS / ABOUT (4)
add("Stats", "Stats · 4 numbers", "📈", sec("cream", '<div class="t6-stats" style="border:0;padding:0">' + "".join(f'<div class="t6-stat"><b>{a}</b><span>{b}</span></div>' for a, b in [("200+", "Completed spaces"), ("10", "Years of practice"), ("45", "People on our team"), ("4.9", "Client rating")]) + "</div>"))
add("Stats", "Stats · dark with text", "🌙", sec("navy", f'<div class="t6-split"><div><p class="t6-k">In numbers</p><h2>A decade of design and build</h2><p>One accountable team — designers, site engineers and craftsmen.</p></div><div class="t6-g g2">' + "".join(f'<div class="t6-stat"><b>{a}</b><span>{b}</span></div>' for a, b in [("2016", "Founded in Lahore"), ("200+", "Spaces delivered"), ("6", "Disciplines"), ("1", "Workshop")]) + "</div></div>"))
add("Content", "About · story split", "📖", sec("", f'<div class="t6-split"><div><p class="t6-k">About Woodex</p><h2>Design and craft under one roof</h2><p>Woodex Interior grew from a furniture workshop into a full design-and-build studio. We still make our own furniture — so every piece fits the space it was designed for.</p>{acts(True,"About us","Our work")}</div>{img(22,"Woodex workshop","tall")}</div>'))
add("Content", "About · values 3", "💎", sec("cream", head("Our values", "How we work", "", True) + '<div class="t6-g g3">' + "".join(f'<div class="t6-card"><span class="t6-num">{i+1:02d}</span><h3>{a}</h3><p>{b}</p></div>' for i, (a, b) in enumerate([("Honest", "Clear budgets and no surprises."), ("Careful", "Details checked on site, every week."), ("Lasting", "Materials and furniture built to last.")])) + "</div>"))
# ---------------- PRICING (3)
pc = [("Consultation", "Free", "Site visit and first ideas", ["Site visit", "Brief & budget", "Next steps"]), ("Design", "PKR / sq ft", "Full design package", ["Concept & 3D", "Drawings", "BOQ"]), ("Turnkey", "Quoted", "Design + build + furniture", ["Everything in Design", "Site teams", "Furniture & handover"])]
price = lambda tone="": '<div class="t6-g g3">' + "".join(f'<div class="t6-card t6-price{" hot" if i == 1 else ""}"><span class="t6-num">{n}</span><b>{p}</b><p>{d}</p><ul class="t6-list">' + "".join(f"<li>{x}</li>" for x in L) + f'</ul><div class="t6-acts"><a class="btn {"wx-btn-light" if i == 1 else "wx-btn-dark"}" href="/contact/">Get a quote</a></div></div>' for i, (n, p, d, L) in enumerate(pc)) + "</div>"
add("Pricing", "Pricing · 3 plans", "💰", sec("", head("Pricing", "Clear packages", "Final price depends on size and finishes — we confirm after a site visit.", True) + price()))
add("Pricing", "Pricing · cream with note", "🧾", sec("cream", head("Packages", "Pick a starting point", "", True) + price()))
add("Pricing", "Pricing · estimator CTA", "🧮", sec("", f'<div class="t6-band" style="background:#f4efe7;color:#12151c"><div><h2>How much will my project cost?</h2><p style="color:#6a6560">Get an instant range with our free cost estimator.</p></div><a class="btn wx-btn-dark" href="/estimator/">Open estimator</a></div>'))
# ---------------- TEAM (3)
team = lambda: '<div class="t6-g g4">' + "".join(f'<div class="t6-team"><img src="/assets/img/img-{I[(i+9) % len(I)]}.webp" alt="{r}" loading="lazy" width="800" height="1000"><h3>Team member</h3><p>{r} · {d}</p></div>' for i, (r, d) in enumerate(TEAM)) + "</div>"
add("Team", "Team · 4 people", "👥", sec("", head("Our team", "The people behind the work", "", True) + team()))
add("Team", "Team · dark", "🌙", sec("navy", head("Team", "Designers, engineers and craftsmen") + team()))
add("Team", "Team · join us", "🤝", sec("cream", f'<div class="t6-split">{img(14,"Team at work","wide")}<div><p class="t6-k">Careers</p><h2>Join the Woodex team</h2><p>We’re always looking for designers, site engineers and craftsmen.</p>{acts(True,"Send your CV","About us","/about/")}</div></div>'))

assert len(T) == 50, len(T)
out = os.path.join(os.path.dirname(__file__), "..", "frontend-v1", "builder", "templates-v26.js")
with open(out, "w") as f:
    f.write("/* Woodex — 50 v26 section templates (generated by tools/gen-templates-v26.py). Classes: t6-* in assets/v1.css */\nwindow.WX_TEMPLATES = " + json.dumps(T, ensure_ascii=False, indent=0) + ";\n")
from collections import Counter; print(len(T), dict(Counter(t["cat"] for t in T)))
