// P18 E: Estimator + Forms admin, AI tone defaults
import pp from "puppeteer-core";
const w = (t) => new Promise((r) => setTimeout(r, t));
const ok = (x, m) => { console.log((x ? "PASS " : "FAIL ") + m); if (!x) process.exitCode = 1; };
const b = await pp.launch({ executablePath: process.env.HOME + "/.cache/pb/al/chromium", args: ["--no-sandbox"], headless: "shell", defaultViewport: { width: 1440, height: 950 } });
const a = await b.newPage(); const errs = []; a.on("pageerror", (e) => errs.push(e.message));
await a.goto("http://127.0.0.1:8080/admin/", { waitUntil: "networkidle0" });
await a.type("input[type=email]", "o@woodex.pk"); await a.type("input[type=password]", ((process.env.WX_PW || "") + "x")); await a.keyboard.press("Enter"); await w(3000);
await a.goto("http://127.0.0.1:8080/admin/#/estimator"); await w(2000);
const n = await a.$$eval(".es-svc", (L) => L.length); ok(n > 0, "estimator services listed: " + n);
const out1 = await a.$eval("#pv-out", (x) => x.textContent); ok(/Rs/.test(out1), "live preview: " + out1);
await a.evaluate(() => { const i = document.querySelector('.es-svc [data-r="premium"]'); i.value = 99999; i.dispatchEvent(new Event("input", { bubbles: true })); });
ok((await a.$eval("#pv-out", (x) => x.textContent)) !== out1, "preview updates on rate change");
await a.screenshot({ path: "/home/user/-marketingwoodex/tools/p18-est.png" });
await a.click("#es-save"); await w(1500);
const js = await a.evaluate(() => fetch("/assets/js/estimator-rates.js?x=" + Date.now()).then((r) => r.text())); ok(/99999/.test(js), "rates file rewritten");
const bad = await a.evaluate(() => { const R = JSON.parse(JSON.stringify(window.WX_RATES)); R.services[0].rates.essential = 5e6; return WXA.api("est_save", { rates: R }); }); ok(!bad.ok, "rejects essential > premium: " + bad.error);
await a.goto("http://127.0.0.1:8080/admin/#/forms"); await w(2000);
const fc = await a.$$eval(".fm-card", (L) => L.map((x) => x.dataset.id)); ok(fc.length >= 5, "form cards: " + fc.join(","));
await a.evaluate(() => { const c = document.querySelector('.fm-card[data-id="contact"]'); c.querySelector("[data-f=alertTo]").value = "sales@woodex.pk"; c.querySelector("[data-f=reply]").checked = false; });
await a.click("#fm-save"); await w(1000);
const g = await a.evaluate(() => WXA.api("forms_get")); const ct = g.forms.find((f) => f.id === "contact");
ok(ct.cfg.alertTo === "sales@woodex.pk" && ct.cfg.reply === false, "form settings saved");
const e2 = await a.evaluate(() => WXA.api("forms_save", { forms: { contact: { alertTo: "nope" } } })); ok(!e2.ok, "bad email rejected");
await a.evaluate(() => WXA.api("forms_save", { forms: { contact: { alertTo: "", waAlert: true, reply: true, replyText: "" } } }));
await a.screenshot({ path: "/home/user/-marketingwoodex/tools/p18-forms.png" });
const cc = await a.evaluate(() => WXA.api("chat_cfg_get").catch(() => ({})));
ok(!cc.ok || (cc.cfg && cc.cfg.tone === "designer" && cc.cfg.noPrices !== false), "AI tone designer + no prices " + JSON.stringify(cc.cfg ? { t: cc.cfg.tone, np: cc.cfg.noPrices } : cc.error));
ok(!errs.length, "no JS errors " + errs.join("|")); await b.close();
