import pp from "puppeteer-core";
const w = (t) => new Promise((r) => setTimeout(r, t)), ok = (x, m) => { console.log((x ? "PASS " : "FAIL ") + m); if (!x) process.exitCode = 1; };
const b = await pp.launch({ executablePath: process.env.HOME + "/.cache/pb/al/chromium", args: ["--no-sandbox"], headless: "shell", defaultViewport: { width: 1440, height: 900 } });
const a = await b.newPage(); await a.goto("http://127.0.0.1:8080/admin/", { waitUntil: "networkidle0" });
await a.type("input[type=email]", "o@woodex.pk"); await a.type("input[type=password]", ((process.env.WX_PW || "") + "x")); await a.keyboard.press("Enter"); await w(2500);
await a.evaluate(() => (location.hash = "#/clients")); await w(1500);
await a.evaluate(() => { const d = document.createElement("div"); d.className = "card"; d.innerHTML = "<div class='tbl-wrap'><table class='tbl'><thead><tr><th>Name</th><th>Amount</th><th>Date</th></tr></thead><tbody>" + Array.from({ length: 30 }, (_, i) => `<tr><td>Row ${i + 1}</td><td>${((i * 7919) % 30 + 1) * 1000}</td><td>2026-0${(i % 9) + 1}-1${i % 9}</td></tr>`).join("") + "</tbody></table></div>"; document.getElementById("view").appendChild(d); });
await w(800);
ok(!!(await a.$(".lp-per select")), "Show N entries selector on 30 rows");
const T = () => "[...document.querySelectorAll('#view table.tbl')].pop()";
const vis = () => a.evaluate(() => [...[...document.querySelectorAll("#view table.tbl")].pop().tBodies[0].rows].filter((x) => x.style.display !== "none").length);
ok(await vis() === 25, "default 25 per page");
await a.evaluate(() => { const s = [...document.querySelectorAll(".lp-per select")].pop(); s.value = "10"; s.dispatchEvent(new Event("change", { bubbles: true })); }); await w(500); ok(await vis() === 10, "10 per page");
await a.evaluate(() => [...[...document.querySelectorAll("#view table.tbl")].pop().tHead.rows[0].cells][1].click()); await w(400);
const first = await a.evaluate(() => [...[...document.querySelectorAll("#view table.tbl")].pop().tBodies[0].rows].filter((r) => r.style.display !== "none").map((r) => +r.cells[1].textContent));
ok(first.every((v, i) => !i || v >= first[i - 1]) && first[0] === 1000, "numeric sort across pages, first = 1000");
await a.evaluate(() => (location.hash = "#/dashboard")); await w(800); await a.evaluate(() => (location.hash = "#/clients")); await w(1200);
ok(await a.evaluate(() => localStorage.getItem("wx-per:#/clients")) === "10", "per-page remembered for the screen");
await a.screenshot({ path: "/home/user/-marketingwoodex/tools/p18-ds-table.png" });
await b.close();
